### ISSUE TITLE
mypy complains about etree._XSLTResultTree

### ISSUE THREAD

**Issue by funkyfuture** [JelleZijlstra/lxml-stubs#2]
i get this error when using the stubs:

```
lxml-stubs/lxml/etree.pyi:60: error: Class lxml.etree._XSLTResultTree has abstract attributes "__bytes__"
lxml-stubs/lxml/etree.pyi:60: note: If it is meant to be abstract, add 'abc.ABCMeta' as an explicit metaclass
```

i don't know how to address this issue as it seems to be caused by `SupportsBytes`. i guess this is related to this issue: python/mypy#4426

Python 3.7.2 & mypy 0.650

**Comment by JelleZijlstra** [comment]
Thanks for your report! I pushed a fix.
